/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as PaymentOrderIdRouteImport } from './routes/payment.$orderId'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as MMerchantIdRouteImport } from './routes/m.$merchantId'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as OrderIdSuccessRouteImport } from './routes/order.$id.success'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentOrderIdRoute = PaymentOrderIdRouteImport.update({
  id: '/payment/$orderId',
  path: '/payment/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MMerchantIdRoute = MMerchantIdRouteImport.update({
  id: '/m/$merchantId',
  path: '/m/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdSuccessRoute = OrderIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/category/$id': typeof CategoryIdRoute
  '/m/$merchantId': typeof MMerchantIdRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/order/$id/success': typeof OrderIdSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/category/$id': typeof CategoryIdRoute
  '/m/$merchantId': typeof MMerchantIdRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/order/$id/success': typeof OrderIdSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/wishlist': typeof WishlistRoute
  '/category/$id': typeof CategoryIdRoute
  '/m/$merchantId': typeof MMerchantIdRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/payment/$orderId': typeof PaymentOrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/order/$id/success': typeof OrderIdSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/search'
    | '/wishlist'
    | '/category/$id'
    | '/m/$merchantId'
    | '/order/$id'
    | '/payment/$orderId'
    | '/product/$id'
    | '/order/$id/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/search'
    | '/wishlist'
    | '/category/$id'
    | '/m/$merchantId'
    | '/order/$id'
    | '/payment/$orderId'
    | '/product/$id'
    | '/order/$id/success'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/orders'
    | '/search'
    | '/wishlist'
    | '/category/$id'
    | '/m/$merchantId'
    | '/order/$id'
    | '/payment/$orderId'
    | '/product/$id'
    | '/order/$id/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  OrdersRoute: typeof OrdersRoute
  SearchRoute: typeof SearchRoute
  WishlistRoute: typeof WishlistRoute
  CategoryIdRoute: typeof CategoryIdRoute
  MMerchantIdRoute: typeof MMerchantIdRoute
  OrderIdRoute: typeof OrderIdRouteWithChildren
  PaymentOrderIdRoute: typeof PaymentOrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$orderId': {
      id: '/payment/$orderId'
      path: '/payment/$orderId'
      fullPath: '/payment/$orderId'
      preLoaderRoute: typeof PaymentOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$merchantId': {
      id: '/m/$merchantId'
      path: '/m/$merchantId'
      fullPath: '/m/$merchantId'
      preLoaderRoute: typeof MMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id/success': {
      id: '/order/$id/success'
      path: '/success'
      fullPath: '/order/$id/success'
      preLoaderRoute: typeof OrderIdSuccessRouteImport
      parentRoute: typeof OrderIdRoute
    }
  }
}

interface OrderIdRouteChildren {
  OrderIdSuccessRoute: typeof OrderIdSuccessRoute
}

const OrderIdRouteChildren: OrderIdRouteChildren = {
  OrderIdSuccessRoute: OrderIdSuccessRoute,
}

const OrderIdRouteWithChildren =
  OrderIdRoute._addFileChildren(OrderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  OrdersRoute: OrdersRoute,
  SearchRoute: SearchRoute,
  WishlistRoute: WishlistRoute,
  CategoryIdRoute: CategoryIdRoute,
  MMerchantIdRoute: MMerchantIdRoute,
  OrderIdRoute: OrderIdRouteWithChildren,
  PaymentOrderIdRoute: PaymentOrderIdRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
